# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs: # aqui é as tarefas passo a passo; # Diretorio atual de trabalho (workdir = raiz)

  test: # rotina de execucao #passo - 1
    strategy:
      matrix:
        go_version: ['1.18', '>=1.20']
    runs-on: ubuntu-latest
    steps: # passo começa com - hifen
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{matrix.go_version}}
      
    # para que seja criada as imagens do docker
    - name: Build-DB
      run: docker-compose build 

    # cria o banco de dados subindo os containers
    - name: Create-DB
      run: docker-compose up -d

    - name: Test
      run: go test -v main_test.go # necessita de um banco de dados, para saber se teve um bug, onde vamos consultar os logs dele

  build:  # rotina de execucao #passo - 2 
    needs: test
    runs-on: ubuntu-latest
    steps: # passo começa com - hifen
      - uses: actions/checkout@v3
      - name: Build
        run: go build -v main.go
    
